version: "3"

services:
    # https://hub.docker.com/r/linuxserver/wireguard
    # A VPN node with WireGuard service and an API exposed over 8008 port, based in FastAPI
    wireguard_api:
      build:
        context: "."
        dockerfile: Dockerfile
      container_name: wireguard_api
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - API_TOKEN=${API_TOKEN}
        - SERVERURL=${VPN_HOSTNAME}
        - SERVERPORT=51820
        - PEERS=0 # peers to be generated
        - PEERDNS=auto # optional
        - INTERNAL_SUBNET=10.13.13.0 # only change if it clashes
        - ALLOWEDIPS=0.0.0.0/0 # change this or ALL traffic will be routed through the VPN
      volumes:
        - /lib/modules:/lib/modules
      networks:
        wireguard_api_subnet:
          aliases:
            - wireguard_api
      ports:
        - 51820:51820/udp
        - 8008:8008
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
      restart: unless-stopped

networks:
  wireguard_api_subnet:
