version: "3"

services:
    # https://hub.docker.com/r/linuxserver/wireguard
    # A VPN node with WireGuard service and an API exposed over 8008 port, based in FastAPI
    wireguard_api:
      build:
        context: "."
        dockerfile: Dockerfile
      container_name: wireguard_api
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      volumes:
        - /lib/modules:/lib/modules
      networks:
        wireguard_api_subnet:
          aliases:
            - wireguard_api
      ports:
        - 51820:${VPN_PORT}/udp
        - 8008:${API_PORT}
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
      restart: unless-stopped

networks:
  wireguard_api_subnet:
